<#macro page>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Библиотека примеров на языке ASP</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            <#nested>
        </div>
    </body>
    </html>
</#macro>